contexts:
    default:
        brokers:
            - localhost:9092
        kafkaversion: 2.1.1
    sivyg8:
        brokers:
            - kafka.sivyg8.private.xyz:9092
        kafkaversion: 2.1.1
current-context: sivyg8
