contexts:
    default:
        brokers:
            - localhost:9092
        kafkaversion: 2.1.1
    xlybbu:
        brokers:
            - kafka.xlybbu.private.xyz:9092
        kafkaversion: 2.1.1
current-context: default
